### ISSUE TITLE
Remove some standard columns and re-order others in export

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#331]
Current order:

1. Sheet ID
2. Name (of Design)
3. Description (of Design)
4. Sheet Creation Date
5. Project
6. Site
7. Subject
8. Acrostic
9. Status
10. Creator
11. Event Name

Proposed new order (off the top of my head):

Note: Status has been deleted in the interim.

**Delete: Description, Project**

1. Subject
2. Acrostic
3. Site
4. Name (of Design)
5. Event Name
6. Sheet ID
7. Creator
8. Sheet Creation Date

**Comment by mcailler** [comment]
I think that's a fairly good order. The only change I'd suggest is removing creator from some exports. The only time I could envision that field being used is to double check all the data entry by someone that we knew messed everything up (and even then it wouldn't track fixes by last_updated_by). I think we can safely leave it out of the SAS/R exports (and potentially others).

Side note: It'd be nice one day be able to get exports with 1 row/subject-event, rather than 1 row/subject-design, a la REDCap exporting

**Comment by remomueller** [comment]
Nice, thanks for the feedback, we'll try this for a list:

1. Subject
2. Acrostic
3. Site
4. Name (of Design)
5. Event Name
6. Sheet ID
7. ~~Creator~~
8. ~~Sheet Creation Date~~
