### ISSUE TITLE
Videos should be viewable in Section variables

### ISSUE THREAD

**Issue by mcailler** [remomueller/slice#616]
Potentially either as an uploaded file or just an embedded link from Vimeo or YouTube

/cc @mrueschman

**Comment by mrueschman** [comment]
Uploaded videos seems a bit ambitious given questions about file size / formats. 

Is embedding the video essential? Is linking to the video in text (to open in a new tab) insufficient?

**Comment by remomueller** [comment]
This may be possible, however it's not possible to use "modern" web technology for YouTube videos. Both YouTube and Vimeo videos can be embedded using iframes, however interacting with iframes differs (example, play/pause/start between both video hosts). Vimeo does allow HTML5 videos, however only if for users of the Vimeo Pro accounts and the video has to be set by the uploader to be embeddable using HTML5 format (not enabled by default).

Knowing this, we could have a shorthand for the video to be embedded using an iframe, something like [youtube:VIDEOID] or [vimeo:VIDEOID]. So for example: [youtube:hzl_4W0Vxds]

Finally, as @mrueschman has alluded to, uploading videos is definitely out of the question due to the large variety of formats, the size (would exceed the 25MB upload limit), and then providing a format back that has the correct resolution for mobile, or even the correct type based on the browser. (Hence why services like YouTube and Vimeo exist in the first place).

**Comment by remomueller** [comment]
I actually just checked, and it's possible for both Vimeo and YouTube to embed videos already. Make sure you're copying the embed code (`<iframe...>`) into the Section Description.
