### ISSUE TITLE
Allow a subset of subjects to be exported for sheets export

### ISSUE THREAD

**Issue by remomueller** [remomueller/slice#625]
- [x] Improve Speed of Exports
- [x] Filter by "Design" and "Event"
- [x] Make sure adverse event "export" also filters only by subjects who have an AE.
- [x] Make sure you can filter by subjects who have been randomized
- [x] All Subjects, Randomized Subjects, Subjects with AEs
- [x] Export filters should link back to sheets index
- [x] Sheets index should allow launching an export based on set filters
- [x] README should reference filters used

**Comment by mrueschman** [comment]
If you wanted something else to aspire for, REDCap allows you to export by Design(s) and Event(s). Would be helpful for users wanting data from one specific form, such that the user would no longer have to fiddle with Excel filters and hiding columns. 😀

![image](https://cloud.githubusercontent.com/assets/707167/26005396/e31ad312-3706-11e7-9732-d3a50d29933b.png)

**Comment by remomueller** [comment]
Good point, I don't think it should add too much complexity, since it saves the settings from your last export now as well.
