### ISSUE TITLE
Export designs without sheets in data dictionary export

### ISSUE THREAD

**Issue by mrueschman** [remomueller/slice#647]
Same as #391 - the "issue" seems to have reappeared.

**Comment by remomueller** [comment]
This is intentional to an extent. When filters are set the Data Dictionary should only describe sheets that are exported. I'll make it so that if you don't provide any filters (Subject Filters, Design Filters, Event Filters, or Sheet Filters) that the Data Dictionary will ignore the "sheet scope", and instead simply load all designs.
